Repository libevent/libevent, pull requests merged in 2020-07, with the labels that each got.

#1048 build: detect and append warning flags only if they are available
  Makefile.am
  configure.ac
  m4/ax_check_compile_flag.m4
Labels: build

#1028 support mbedtls
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/mingw.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  LICENSE
  Makefile.am
  bufferevent-internal.h
  bufferevent_mbedtls.c
  bufferevent_openssl.c
  bufferevent_ssl.c
  cmake/FindMbedTLS.cmake
  configure.ac
  event-config.h.cmake
  include/event2/bufferevent_ssl.h
  include/event2/visibility.h
  libevent_mbedtls.pc.in
  m4/libevent_mbedtls.m4
  sample/include.am
  sample/ssl-client-mbedtls.c
  ssl-compat.h
  test-export/test-export.c
  test-export/test-export.py
  test/include.am
  test/regress.h
  test/regress_main.c
  test/regress_mbedtls.c
  test/regress_openssl.c
  test/regress_ssl.c
Labels: subsystem:ssl

#1063 windows socketpair tmpfile: use random prefix
  evutil.c
Labels: os:windows
