Repository libevent/libevent, pull requests merged in 2022-07, with the labels that each got.

#1291 Fix some OpenSSL 3 test issues.
  test/regress_openssl.c
  test/regress_ssl.c
Labels: subsystem:ssl

#1297 Fix -Werror and run builds with -Werror on CI
  .github/workflows/linux.yml
  CMakeLists.txt
  bufferevent-internal.h
  configure.ac
  event-config.h.cmake
  evthread-internal.h
  http.c
  test/regress_util.c
Labels: ci, build

#1298 Fix autodetection of openssl location via brew
  .github/workflows/macos.yml
  m4/libevent_openssl.m4
Labels: ci, build

#1288 Initial OpenSSL 3.0 support
  .github/workflows/linux.yml
  bufferevent_openssl.c
  m4/libevent_openssl.m4
  sample/becat.c
  sample/le-proxy.c
  test/regress_mbedtls.c
  test/regress_ssl.c
Labels: subsystem:ssl

#1302 Rework CI to keep everything in one workflow (by using reusable workflow)
  .github/workflows/abi.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doxygen.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/master.yml
  .github/workflows/mingw.yml
  .github/workflows/windows.yml
Labels: ci
